### ISSUE TITLE
zabbix 3.4 bareos 17.2 ubuntu 16.04

### ISSUE THREAD

**Issue by nik-weter** [appsinet/bareos-zabbix#1]
I created this config:
  mailcommand = "/var/spool/bareos/bareos-zabbix.bash %i"
  mail = 127.0.0.1 = all, !skipped

Now I always have error:
 Message delivery ERROR: Mail program terminated in error.
                                             CMD=/var/spool/bareos/bareos-zabbix.bash 51
                                             ERR=Child exited with code 63

Maybe you know what does it mean?

**Comment by cmmata** [comment]
What's the output if you execute that script in command-line?
`/var/spool/bareos/bareos-zabbix.bash JobID`

You can also take a look at [this alternative](https://github.com/paleg/bareos_zabbix_integration.git). That's the one that I'm using in a production server.

**Comment by nik-weter** [comment]
Very sorry! The name bareos and zabbix client weren't same. After correction all work fine!
Thanks!

**Comment by cmmata** [comment]
So problem solved! 😊 Don't worry. Closing the issue
